postgres:
  image: postgres:9.5.3
  environment:
    POSTGRES_USER: squareplutonium
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5432:5432'
  volumes:
    - squareplutonium-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.2.1
  ports:
    - '6379:6379'
  volumes:
    - squareplutonium-redis:/var/lib/redis/data

squareplutonium:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/squareplutonium
  ports:
    - '8000:8000'
  env_file:
    - .square-plutonium.env

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/squareplutonium
  env_file:
    - .square-plutonium.env
